name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Instalar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Instalar Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # Aceitar licen√ßas
      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      # Build Debug e Release
      - name: Build Debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Build Release
        run: ./gradlew assembleRelease --stacktrace

      # Upload dos APKs como artefatos
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: MasterTV-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: MasterTV-release
          path: app/build/outputs/apk/release/*.apk
